version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-pwa
    versions:
    - 5.1.4
    - 5.2.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.18
    - 6.1.20
    - 6.2.7
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.15
    - 7.13.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.2.7
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 6.0.0
  - dependency-name: next
    versions:
    - 10.0.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.31
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: storybook-addon-next-router
    versions:
    - 2.0.4
  - dependency-name: lint-staged
    versions:
    - 10.5.4
